name: Convert MSI to MSIX

on:
  push:
    branches: [main]

  workflow_dispatch: null

jobs:
  convert:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup lessmsi
        shell: bash
        run: |
          curl -L -O https://github.com/activescott/lessmsi/releases/download/v2.1.1/lessmsi-v2.1.1.zip
          unzip lessmsi-v2.1.1.zip -d lessmsi

      - name: Download MSIX Hero
        shell: bash
        run: |
          curl -L -O https://sparrowassets.blob.core.windows.net/devops/msix-hero-bins.zip
          unzip msix-hero-bins.zip -d msix_hero
          ls
          ls msix_hero

      - name: Unpack MSI file
        shell: bash
        run: |
          lessmsi/lessmsi x Sparrow_2.3.0_x64_en-US.msi unpacked_msi/

      - name: Repack MSI with MSIX Hero
        shell: bash
        run: |
          msix_hero/msixherocli.exe -i unpacked_msi -o output.msix

      - name: Upload MSIX package
        uses: actions/upload-artifact@v3
        with:
          name: msix-package
          path: output.msix
